name: Build PR
on:
  pull_request

jobs:
  build:
    name: Checkout code and buold
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Java 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          architecture: x64
          cache: 'gradle'
      - name: Build
        run: |
          ./gradlew clean build
